kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: lizheming/drone-coveralls
    when:
      event: tag
      branch:
      - master